services:
  - type: web
    name: food-blood-sugar-analyzer-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        value: postgresql://blood_sugar_analyzer_development_user:tFMy31ZofCXURmzGF6JrnMNSjaBQfE4s@dpg-d26v10ogjchc73elprd0-a.oregon-postgres.render.com:5432/blood_sugar_analyzer_development
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: DEBUG
        value: false
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: Food & Blood Sugar Analyzer API 