"""update_glucose_reading_model_unit_field

Revision ID: 183fb80fea68
Revises: 5ffab80857b6
Create Date: 2025-07-28 09:57:08.440158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '183fb80fea68'
down_revision: Union[str, Sequence[str], None] = '5ffab80857b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_readings', sa.Column('unit', sa.String(), nullable=False, server_default=sa.text("'mg/dl'")))
    op.add_column('glucose_readings', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('glucose_readings', 'source')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_readings', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('glucose_readings', 'note')
    op.drop_column('glucose_readings', 'unit')
    # ### end Alembic commands ###
