"""Add is_admin, weight, weight_unit to User

Revision ID: 5ffab80857b6
Revises: 869d1263854f
Create Date: 2025-07-24 08:37:26.249970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffab80857b6'
down_revision: Union[str, Sequence[str], None] = '869d1263854f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('note', sa.String(), nullable=True))
    op.add_column('activities', sa.Column('calories_burned', sa.Float(), nullable=True))
    op.add_column('meal_ingredients', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('meal_ingredients', sa.Column('carbs', sa.Float(), nullable=False))
    op.add_column('meal_ingredients', sa.Column('glycemic_index', sa.Float(), nullable=True))
    op.add_column('meal_ingredients', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('meal_ingredients', 'quantity')
    op.add_column('meals', sa.Column('total_weight', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('total_carbs', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('glycemic_index', sa.Float(), nullable=True))
    op.add_column('meals', sa.Column('note', sa.String(), nullable=True))
    op.drop_column('meals', 'carbs')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('users', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('weight_unit', sa.String(), nullable=False, server_default=sa.text("'kg'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_unit')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'is_admin')
    op.add_column('meals', sa.Column('carbs', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('meals', 'note')
    op.drop_column('meals', 'glycemic_index')
    op.drop_column('meals', 'total_carbs')
    op.drop_column('meals', 'total_weight')
    op.add_column('meal_ingredients', sa.Column('quantity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('meal_ingredients', 'note')
    op.drop_column('meal_ingredients', 'glycemic_index')
    op.drop_column('meal_ingredients', 'carbs')
    op.drop_column('meal_ingredients', 'weight')
    op.drop_column('activities', 'calories_burned')
    op.drop_column('activities', 'note')
    # ### end Alembic commands ###
