"""add meal_type field to meals table

Revision ID: adf5218d6a2e
Revises: a076cccc29a9
Create Date: 2025-08-08 09:06:51.162893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adf5218d6a2e'
down_revision: Union[str, Sequence[str], None] = 'a076cccc29a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('meal_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'meal_type')
    # ### end Alembic commands ###
