"""Add predefined meals

Revision ID: d1c68a88bac0
Revises: adf5218d6a2e
Create Date: 2025-08-09 14:42:01.835303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1c68a88bac0'
down_revision: Union[str, Sequence[str], None] = 'adf5218d6a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predefined_meals', sa.Column('owner_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'predefined_meals', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'predefined_meals', type_='foreignkey')
    op.drop_column('predefined_meals', 'owner_user_id')
    # ### end Alembic commands ###
