"""add_meal_context_to_glucose_readings

Revision ID: ddac211329f5
Revises: add_reset_token_fields
Create Date: 2025-08-07 09:29:53.180715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ddac211329f5'
down_revision: Union[str, Sequence[str], None] = 'add_reset_token_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glucose_readings', sa.Column('meal_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('users', 'reset_token_expires',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reset_token_expires',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('glucose_readings', 'meal_context')
    # ### end Alembic commands ###
