"""add_start_time_end_time_to_activities

Revision ID: e77cca3e01cd
Revises: 183fb80fea68
Create Date: 2025-07-29 22:49:16.601582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77cca3e01cd'
down_revision: Union[str, Sequence[str], None] = '183fb80fea68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('activities', sa.Column('end_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'end_time')
    op.drop_column('activities', 'start_time')
    # ### end Alembic commands ###
